apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyterhub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyterhub 
  template:
    metadata:
      labels:
        app: jupyterhub
    spec:
      containers:
      - name: jupyterhub
        image: jupyterhub/jupyterhub
---
apiVersion: v1
kind: Service
metadata:
  name: jupyterhub-service
spec:
  ports:
  - name: http
    port: 8000           
    targetPort: 8000
  selector:
    app: jupyterhub          
  type: LoadBalancer   
