apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus 
  template:
    metadata:
      labels:
        app: nexus
    spec:
      containers:
      - name: nexus
        image: sonatype/nexus3
---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  ports:
  - name: http
    port: 8081           
    targetPort: 8081   
  selector:
    app: nexus          
  type: LoadBalancer   
